name: Dev Build & Push
on:
  schedule:
    - cron: '0 7 * * *'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        if: github.event_name == 'schedule'
        uses: actions/checkout@v3
        with:
          ref: main
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.DOCKERHUB_NAMESPACE }}/pihole-bind
          flavor: |
            latest=false
          tags: |
            type=schedule,pattern=dev
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./dev/
          platforms: linux/amd64, linux/arm64, linux/arm/v7, linux/arm/v6, linux/386
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=registry,ref=${{ secrets.DOCKERHUB_NAMESPACE }}/pihole-bind:buildcache.dev
          cache-to: |
            type=registry,ref=${{ secrets.DOCKERHUB_NAMESPACE }}/pihole-bind:buildcache.dev,mode=max
